input_vars: ${input_vars}
positional_vars : ${positional_vars}
#lr: 0.001
#weight_decay: 0.000001: 
#loss: 'ce'
#encoder: 'efficientnet-b1'
_target_: src.models.model.PPNet
#base_architecture: "unet"
image_size: 128
prototype_shape: [20, 64, 1, 1]
num_classes: 2
#features : ${hydra:call:src.models.seasfire_unet_module.unet_features}
proto_layer_rf_info : []
#pretrained: true
prototype_activation_function: "cos"  # "linear" "log"
add_on_layers_type: 'deeplab_simple'
bottleneck_stride: null
patch_classification: True
norm_proto: True


