defaults:
  - model_checkpoint.yaml
#  - early_stopping.yaml
#  - model_summary.yaml
#  - rich_progress_bar.yaml
  - add_metric_aggs.yaml
  - log_val_predictions_segmentation
  - _self_

add_metric_aggs:
  _target_: src.callbacks.wandb_callbacks.AddMetricAggs
  metrics: ["val/loss", "val/auprc", "val/f1", "val/auroc"]
  aggs: ["min", "max", "max", "max"]

log_val_predictions_segmentation:
  num_samples: 8
  every_n_epochs: 10

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False
#  every_n_epochs: 10
#
#early_stopping:
#  monitor: "val/acc"
#  patience: 100
#  mode: "max"
#
#model_summary:
#  max_depth: -1
